# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/VIVADO_program/FIR_filter_U060/FIR_filter/FIR_filter.cache/wt [current_project]
set_property parent.project_path F:/VIVADO_program/FIR_filter_U060/FIR_filter/FIR_filter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  F:/VIVADO_program/FIR_filter_U060/FIR_filter/sin_wave.v
  F:/VIVADO_program/FIR_filter_U060/FIR_filter/FIR.v
  F:/VIVADO_program/FIR_filter_U060/FIR_filter/div_clk.v
  F:/VIVADO_program/FIR_filter_U060/FIR_filter/sin_noise.v
  F:/VIVADO_program/FIR_filter_U060/FIR_filter/FIR_filter.v
}
synth_design -top FIR_filter -part xc7a200tfbv676-1
write_checkpoint -noxdef FIR_filter.dcp
catch { report_utilization -file FIR_filter_utilization_synth.rpt -pb FIR_filter_utilization_synth.pb }
